# Build settings

markdown: kramdown
permalink: none
plugins:             [jekyll-sitemap, jekyll-feed,  jekyll-seo-tag]

port: 4000

sass:
  sass_dir: assets/css
  style: :nested

# Customise atom feed settings (this is where Jekyll-Feed gets configuration information)

title:		           "All the Basic of Nayoung"
subtitle:            "Journey to the Ultimate Programmer"
description:	       "Slowly takes a step to Programming"
author:              "Nayoung Bae"
baseurl : /
url : https://nayoung511.github.io/
